language: node_js
node_js
  - "18"
install:
  - npm install
deploy 
  provider: NPM
  #email: zhangqiangzgz@hotmail.com
  api_key: travis encrypt NPM_TOKEN --add deploy.api_key --com
  cleanup: true
branches:
  only:
    - main