language: node_js
node_js:
 - 18
before_install: 
 - npm install pnpm
install:
 - pnpm install
script:
 - pnpm run build
deploy:
 provider: npm
 email: zhangqiangzgz@hotmail.com
 api_token: <encrypted api_token>
 registry: https://registry.npmjs.org/
 cleanup: true
 edge: true # opt in to dpl v2
branches:
 only:
  - main